# Generated by Django 4.2.5 on 2023-10-27 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mambo', '0008_remove_category_category_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='items_in_a_category',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
