# Generated by Django 4.2.5 on 2023-11-10 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mambo', '0009_alter_category_items_in_a_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='photo',
            field=models.ImageField(default=0, upload_to='photos/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='items_in_a_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
