# Generated by Django 4.2.5 on 2023-11-13 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mambo', '0010_dish_photo_alter_category_items_in_a_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.CharField(blank=True, choices=[('M D', 'MAIN DISH'), ('C D', 'COLD DRINKS'), ('T', 'TEA'), ('D', 'DISSERTS')], max_length=100, null=True),
        ),
    ]
