# Generated by Django 4.2.5 on 2023-11-24 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mambo', '0011_alter_category_category_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='items_in_a_category',
        ),
    ]
