# Generated by Django 4.2.5 on 2023-11-24 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mambo', '0013_category_items_in_a_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='items_in_a_category',
        ),
    ]
